---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: 18fgsa/pulledpork

inputs:
- name: snort-jammy-release-source

outputs:
- name: snort-pulledpork-source

run:
  path: snort-jammy-release-source/ci/tasks/jammy-pulledpork.sh
