---
platform: linux

image_resource:
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: pulledpork
    aws_region: us-gov-west-1
    tag: latest

inputs:
- name: snort-release-source

outputs:
- name: snort-pulledpork-source

run:
  path: snort-release-source/ci/tasks/pulledpork.sh
