---
jobs:

- name: update-release-git
  plan:
  - get: snort-release-source
    trigger: true
  - get: snort-blobs-yml
  - get: final-builds-dir-tarball
  - get: releases-dir-tarball
  - get: general-task
  - task: pulledpork
    file: snort-release-source/ci/tasks/pulledpork.yml
    params:
      OINKCODE: ((oinkcode))
      SNORT_VERSION: ((snort-version))
  - task: update-blobs
    image: general-task
    file: snort-release-source/ci/tasks/update-release.yml
    tags: [iaas]
    params:
      PRIVATE_YML: ((private-yml))
      FORCE_UPDATE: 1
  - in_parallel:
    - put: snort-blobs-yml
      tags: [iaas]
      params:
        file: snort-bosh-source/config/blobs.yml
    - put: release-tarball
      tags: [iaas]
      params:
        file: finalized-release/jammy-snort-*.tgz
    - put: final-builds-dir-tarball
      tags: [iaas]
      params:
        file: finalized-release/final-builds-dir-jammy-snort.tgz
    - put: releases-dir-tarball
      tags: [iaas]
      params:
        file: finalized-release/releases-dir-jammy-snort.tgz

- name: update-release-rules
  plan:
  - get: timer
    trigger: true
  - get: snort-release-source
  - get: snort-blobs-yml
  - get: final-builds-dir-tarball
  - get: releases-dir-tarball
  - get: general-task
  - task: pulledpork
    file: snort-release-source/ci/tasks/pulledpork.yml
    params:
      OINKCODE: ((oinkcode))
      SNORT_VERSION: ((snort-version))
  - task: update-blobs
    image: general-task
    file: snort-release-source/ci/tasks/update-release.yml
    tags: [iaas]
    params:
      PRIVATE_YML: ((private-yml))
      FORCE_UPDATE: 0
  - in_parallel:
    - put: snort-blobs-yml
      tags: [iaas]
      params:
        file: snort-bosh-source/config/blobs.yml
    - put: release-tarball
      tags: [iaas]
      params:
        file: finalized-release/jammy-snort-*.tgz
    - put: final-builds-dir-tarball
      tags: [iaas]
      params:
        file: finalized-release/final-builds-dir-jammy-snort.tgz
    - put: releases-dir-tarball
      tags: [iaas]
      params:
        file: finalized-release/releases-dir-jammy-snort.tgz

resources:
- name: timer
  type: time
  source:
    interval: 1h

- name: snort-release-source
  type: git
  source:
    uri: ((snort-release-uri))
    branch: ((snort-release-branch))
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: snort-blobs-yml
  type: s3-iam
  source:
    region_name: ((s3-bosh-releases-region))
    bucket: ((s3-bosh-releases-bucket))
    versioned_file: jammy-snort-blobs.yml
    server_side_encryption: AES256
    endpoint: s3-fips.((s3-bosh-releases-region)).amazonaws.com

- name: release-tarball
  type: s3-iam
  source:
    region_name: ((s3-bosh-releases-region))
    bucket: ((s3-bosh-releases-bucket))
    regexp: jammy-snort-(.*).tgz
    server_side_encryption: AES256
    endpoint: s3-fips.((s3-bosh-releases-region)).amazonaws.com

- name: final-builds-dir-tarball
  type: s3-iam
  source:
    bucket: ((s3-bosh-releases-bucket))
    versioned_file: final-builds-dir-jammy-snort.tgz
    region_name: ((s3-bosh-releases-region))
    server_side_encryption: AES256
    endpoint: s3-fips.((s3-bosh-releases-region)).amazonaws.com

- name: releases-dir-tarball
  type: s3-iam
  source:
    bucket: ((s3-bosh-releases-bucket))
    versioned_file: releases-dir-jammy-snort.tgz
    region_name: ((s3-bosh-releases-region))
    server_side_encryption: AES256
    endpoint: s3-fips.((s3-bosh-releases-region)).amazonaws.com

- name: general-task
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: general-task
    aws_region: us-gov-west-1
    tag: latest

resource_types:
- name: registry-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: registry-image-resource
    aws_region: us-gov-west-1
    tag: latest

- name: s3-iam
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: s3-resource
    aws_region: us-gov-west-1
    tag: latest

- name: time
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: time-resource
    aws_region: us-gov-west-1
    tag: latest

- name: git
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: git-resource
    aws_region: us-gov-west-1
    tag: latest
